export interface SpottEvent {
  id: string;
  title: string;
  description: string;
  date: string;
  endDate?: string;
  price: number;
  status: string;
  organizer: string;
  verified: boolean;
  location: string;
  address?: string;
  city: string;
  latitude?: number;
  longitude?: number;
  categories: string[];
  registrations: number;
  confirmedAt: string | null;
  isSaved?: boolean;
}

export const DEFAULT_EVENTS: SpottEvent[] = [
  {
    id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    title: "Rizal Park Night Market & Food Bazaar",
    description: "Experience the best of Filipino street food and artisan goods at the iconic Rizal Park. Over 50 vendors, live acoustic music, and family-friendly activities.",
    date: "2026-09-14 17:00:00",
    endDate: "2026-09-14 23:00:00",
    price: 0,
    status: "active",
    organizer: "Spott Manila",
    verified: true,
    location: "Rizal Park",
    address: "Rizal Park, Manila",
    city: "Manila",
    latitude: 14.5831,
    longitude: 120.9794,
    categories: ["Night Markets", "Food", "Community"],
    registrations: 42,
    confirmedAt: "2026-09-14 10:00:00",
  },
  {
    id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
    title: "UP College Fair 2026: Dawn",
    description: "Annual university fair featuring student organizations, academic booths, cultural performances, and campus tours.",
    date: "2026-09-20 08:00:00",
    endDate: "2026-09-20 17:00:00",
    price: 0,
    status: "active",
    organizer: "UP Diliman",
    verified: true,
    location: "UP Diliman Sunken Garden",
    address: "UP Diliman, Quezon City",
    city: "Quezon City",
    latitude: 14.6537,
    longitude: 121.0685,
    categories: ["School Events", "Music"],
    registrations: 110,
    confirmedAt: "2026-09-20 08:00:00",
  },
  {
    id: "cccccccc-cccc-cccc-cccc-cccccccccccc",
    title: "Indie Folk Sessions: Escolta",
    description: "An intimate evening of indie folk music featuring up-and-coming Filipino artists. Limited seating for an exclusive acoustic experience.",
    date: "2026-09-15 19:30:00",
    endDate: "2026-09-15 22:30:00",
    price: 200,
    status: "active",
    organizer: "Escolta Creative Hub",
    verified: true,
    location: "Route 196, Katipunan",
    address: "Katipunan Ave, Quezon City",
    city: "Quezon City",
    latitude: 14.6312,
    longitude: 121.0745,
    categories: ["Concerts", "Music"],
    registrations: 34,
    confirmedAt: null,
  },
  {
    id: "dddddddd-dddd-dddd-dddd-dddddddddddd",
    title: "UI/UX Design Workshop",
    description: "Hands-on workshop covering modern UI/UX principles, Figma prototyping, and user research methods.",
    date: "2026-09-17 14:00:00",
    endDate: "2026-09-17 17:00:00",
    price: 500,
    status: "active",
    organizer: "Design Guild PH",
    verified: false,
    location: "Makati, Online/Hybrid",
    address: "5th Ave, BGC / Online",
    city: "Makati",
    latitude: 14.5515,
    longitude: 121.0497,
    categories: ["Workshops", "Tech"],
    registrations: 18,
    confirmedAt: null,
  },
  {
    id: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
    title: "Barangay Sports Fest",
    description: "Community sports day featuring basketball, volleyball, fun runs, and family relay races. Free entry, open to all ages.",
    date: "2026-09-21 06:00:00",
    endDate: "2026-09-21 18:00:00",
    price: 0,
    status: "active",
    organizer: "QC Sports Dev",
    verified: true,
    location: "Quezon Memorial Circle",
    address: "Elliptical Road, Quezon City",
    city: "Quezon City",
    latitude: 14.6517,
    longitude: 121.0490,
    categories: ["Sports", "Community"],
    registrations: 65,
    confirmedAt: "2026-09-21 06:00:00",
  },
  {
    id: "ffffffff-ffff-ffff-ffff-ffffffffffff",
    title: "Street Food Bazaar",
    description: "Weekend food crawl featuring the best street food vendors from across Metro Manila.",
    date: "2026-09-19 16:00:00",
    endDate: "2026-09-19 22:00:00",
    price: 0,
    status: "active",
    organizer: "BGC Events",
    verified: false,
    location: "BGC, Taguig",
    address: "Circuit Lane, Makati",
    city: "Taguig",
    latitude: 14.5533,
    longitude: 121.0195,
    categories: ["Food & Drink", "Food"],
    registrations: 88,
    confirmedAt: null,
  },
  {
    id: "11111111-0000-0000-0000-000000000001",
    title: "Lakeside Farmers Market",
    description: "Fresh produce, organic goods, artisan crafts, and farm-to-table delights.",
    date: "2026-10-14 08:00:00",
    endDate: "2026-10-14 14:00:00",
    price: 0,
    status: "active",
    organizer: "Suburbs Community Collective",
    verified: true,
    location: "Lakeside Park",
    address: "Lakeside Park",
    city: "Manila",
    latitude: 14.5896,
    longitude: 120.9750,
    categories: ["Markets", "Food"],
    registrations: 42,
    confirmedAt: "2026-10-14 08:00:00",
  },
  {
    id: "11111111-0000-0000-0000-000000000002",
    title: "Riverside Open Mic Night",
    description: "Bring your guitar, your poems, or just your ears. Open mic night for musicians, poets, and storytellers.",
    date: "2026-10-17 20:00:00",
    endDate: "2026-10-17 23:00:00",
    price: 15,
    status: "active",
    organizer: "Pop & Indie Festivals",
    verified: false,
    location: "Riverside Stage",
    address: "Riverside Stage",
    city: "Quezon City",
    latitude: 14.6567,
    longitude: 121.0302,
    categories: ["Concerts", "Music"],
    registrations: 128,
    confirmedAt: null,
  },
  {
    id: "11111111-0000-0000-0000-000000000003",
    title: "Urban Sketching Fundamentals",
    description: "Learn the basics of urban sketching with professional artists. All materials provided.",
    date: "2026-10-20 10:00:00",
    endDate: "2026-10-20 12:00:00",
    price: 0,
    status: "active",
    organizer: "City Arts Society",
    verified: true,
    location: "City Arts Hub",
    address: "City Arts Hub",
    city: "Manila",
    latitude: 14.5896,
    longitude: 120.9750,
    categories: ["Workshops", "Art"],
    registrations: 25,
    confirmedAt: null,
  },
];
